version: '3.6'
services:
  sensor:
    build: ./sensor
    network_mode: "host"
    privileged: true
    devices:
      - /dev/gpiochip0
    volumes:
      - ./sensor/start.sh:/start.sh
      - ./sensor/sensor.py:/sensor.py
      - ./sensor/DHT22.py:/DHT22.py

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '0.0.0.0:8125:8125/udp'

  influxdb:
    image: influxdb:1.8
    env_file: configuration.env
    ports:
      - '0.0.0.0:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '0.0.0.0:3000:3000'
    expose:
      - '3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana_data: { }
  influxdb_data: { }
