version: '3.6'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6.13
    restart: always
    ports:
      - '1883:1883'
      - '9001:9001'
    networks:
      - iot
    expose:
      - '1883'

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mosquitto
    links:
      - influxdb
      - mosquitto
    ports:
      - '8125:8125/udp'
    networks:
      - iot

  influxdb:
    image: influxdb:1.8
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    networks:
      - iot

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - iot

networks:
  iot:

volumes:
  grafana_data: { }
  influxdb_data: { }
